NEXT_PUBLIC_PRICE_FEED_AGGREGATOR_URL = "wss://pismoprotocol-production.up.railway.app"
NEXT_PUBLIC_BACKEND_API_URL = "http://127.0.0.1:5080"
NEXT_PUBLIC_SUI_PACKAGE_ID = "0x4d946f961b9cf4a1d0bc8df32cd2502b4907b73f77d097bb090cca96be598a1b"
NEXT_PUBLIC_SUI_GLOBAL_OBJECT_ID = "0x11d6f695c83195583fa08bc76e9b689ae7b27c1b56159eafe543784153be14af"
NEXT_PUBLIC_SUI_PROGRAM_OBJECT_ID = "0xdb2e4650cd78afbc0919471c3db9b7187f07dae73018c96367add1366afad29a"
NEXT_PUBLIC_SUI_EXPLORER_BASE_URL = "https://suiscan.xyz/testnet/tx/"
NEXT_PUBLIC_INDEXER_URL = "http://127.0.0.1:3001"
