[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r price-feed-aggregator/requirements.txt && pip install -e price-feed-aggregator"
]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && python -m price-feed-aggregator.src.main --host 0.0.0.0 --port ${PORT:-8765} --api-host 0.0.0.0 --api-port ${API_PORT:-8080}" 