database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0xfbfe8ff68af3761519abd50624b8d8181a0b46a433b852f3b5ab1d818e8e6f76"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 199_190_916
concurrency = 5
listen_addr = "0.0.0.0:3001"
liquidation_transfer_service_url = "http://localhost:3002"
