database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0x24a0482ca1fdfc667414dfd9ebceaf33ccbb1f35eed88412206e32c64a11dc7c"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 196_925_181
concurrency = 5
listen_addr = "0.0.0.0:3001"
