database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0x3394b2c932c710286fd2400c984df91a536f3ab72bc2d0657e98214defb1ab79"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 196_901_353
concurrency = 5
listen_addr = "0.0.0.0:3001"
