database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0xc93a7b65baee3a6c143a5ca27bfb28cf4414cd0477dd24e6ac768ce9a4015da0"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 192_696_118
concurrency = 5
listen_addr = "0.0.0.0:3001"
