database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0x4ccbc5f1897ae7f970c5d7436c4b578106ce9b89afd7006fa717aa19cefd037b"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 199_227_262
concurrency = 5
listen_addr = "0.0.0.0:3001"
liquidation_transfer_service_url = "http://localhost:3002"
