database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0xb8ec5f67c3a0341d73fed6e525585ce686b1f5d82382a99cad7d3c056a95153f"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 199_209_514
concurrency = 5
listen_addr = "0.0.0.0:3001"
liquidation_transfer_service_url = "http://localhost:3002"
