# Configuration for the Indexer (Testnet)

# Connection string for the PostgreSQL database
database_url = "postgresql://postgres:postgres@localhost:7654/indexer"

# Deployed Package ID of the pismo_protocol module
package_id = "0xdb094aafef09a5925a71ac418279bab3196e1153d3c3d93c23154390d883ca01"

# URL of the Sui remote checkpoint store (e.g., testnet, mainnet)
remote_store_url = "https://checkpoints.testnet.sui.io"

# Checkpoint sequence number to start indexing from
start_checkpoint = 189253799

# Number of concurrent checkpoint processing tasks
# Adjust based on your machine resources and workload
concurrency = 5

# Address and port for the API server to listen on
listen_addr = "0.0.0.0:3001" 