database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0x805b0d2f375082fc03c5f158e963aa1ab59f5a5a042fae16056b45336acdc099"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 198_067_716
concurrency = 5
listen_addr = "0.0.0.0:3001"
liquidation_transfer_service_url = "http://localhost:3002"
