database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0xd0da58a18c42db096b9fb3e910fc2c56728a36238d749d348b54387fcfbc58c0"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 198_889_745
concurrency = 5
listen_addr = "0.0.0.0:3001"
liquidation_transfer_service_url = "http://localhost:3002"
