database_url = "postgresql://postgres:postgres@localhost:7654/indexer"
package_id = "0xb30cbea87357343b279887389af76ed1f0a9656cef7a9840ca6cdc5f3ec16d05"
remote_store_url = "https://checkpoints.testnet.sui.io"
start_checkpoint = 195_745_778
concurrency = 5
listen_addr = "0.0.0.0:3001"
