version: '3.8'

services:
  price-feed-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: price-feed-aggregator-prod
    ports:
      - "8765:8765"  # WebSocket server
      - "8080:8080"  # REST API
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - PYTH_SSE_URL=https://hermes.pyth.network/v2/updates/price/stream
    restart: always
    networks:
      - price-feed-network
    volumes:
      # Mount logs directory for persistence
      - price-feed-logs:/app/logs
      # Mount certificates if needed
      - ./certificates:/app/certificates:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: price-feed-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - price-feed-aggregator
    networks:
      - price-feed-network
    restart: always
    profiles:
      - with-proxy

networks:
  price-feed-network:
    driver: bridge

volumes:
  price-feed-logs:
    driver: local
