[package]
name = "avila"
version = "1.0.0"
authors = []

[addresses]
avila = "_"

[dev-addresses]
avila = "0xDEADBEEF"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
